version: "3.9"
services:
    userservice:
        build: ./UserServiceGrpc
        container_name: UserServiceContainer
        ports:
            - "5001:5001"
    productservice:
        build: ./ProductServiceGrpc
        container_name: ProductServiceContainer
        ports:
            - "5002:5002"
    apigateway:
        build: ./API Gateway
        container_name: APIGatewayContainer
        ports:
            - "5003:5003"
        depends_on:
            - userservice
            - productservice
    