version: "3.9"
services:
    #microservices    
    userservice:
        build: ./UserServiceGrpc
        container_name: UserServiceContainer
        ports:
            - "5001:5001"
    productservice:
        build: ./ProductServiceGrpc
        container_name: ProductServiceContainer
        ports:
            - "5002:5002"
    orderservice:
        build: ./OrderServiceGrpc
        container_name: OrderServiceContainer
        ports:
            - "5004:5004"
    apigateway:
        build: ./API Gateway
        container_name: APIGatewayContainer
        ports:
            - "5003:5003"
        depends_on:
            - userservice
            - productservice
            - orderservice  
    #Kafka Message Broker
    kafka:
        image: apache/kafka:latest
        container_name: kafka_broker
        hostname: kafka
        ports:
          - "9092:9092" # Kafka broker for host apps
        environment:
          # KRaft mode (no ZooKeeper needed)
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_NODE_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          CLUSTER_ID: CLDcN5CdTnGm0bb54IBa7A # generate once using kafka-storage
        volumes:
          - ./kafka-data:/tmp/kraft-combined-logs
    
    